### ISSUE TITLE
Question about design

### ISSUE THREAD

**Issue by NobbZ** [whitfin/unsafe#2]
Is there a reasom why you have choosen a module attribute that I have to maintain distinctly to the actual functions?

Why don't you use a new macro for function defintion, like `def!`, `defbang`, or `defunsafe`? This would keep definition of the function and declaration if it is unsafe at the same place.

**Comment by whitfin** [comment]
Hey @NobbZ,

It's interesting; before I wrote this I actually had a similar syntax. The issue comes mainly when you want to provide options (such as a handler), or you have clashing function definitions. Imagine if you had a situation where your first argument was handled differently based on type - you couldn't use `def!` on both definitions.

Maybe you have an example snippet of what you're thinking of? I can address is specifically.

**Comment by NobbZ** [comment]
When you previously used `{:foo, 0}`, just use `defbang`, when you previously used `{:foo, 0, :handler}` now use this:

```
@handler :handler
defbang foo(), do: …
```

As an additional special case also `@handler true` where possible which implies the name as `handle_foo`.

This way everything can stay close together.

**Comment by whitfin** [comment]
@NobbZ ok, I see. This is already supported as there's nothing stopping you keeping it closer together this way:

```elixir
@unsafe foo: 1
def foo(value), do: ...
```

This is basically the same as you put above, except without the unnecessary `defbang` macro.

**Comment by NobbZ** [comment]
Ah, OK, I didn't realize that the attribute is cummulative.

Thank you!
